# data_gen/misc_data.toml
#
# Copyright (C) 2025-2026 James Petersen <m@jamespetersen.ca>
# Licensed under MIT. See LICENSE

loc_table.base = 0
loc_table.overworld = 1
loc_table.hidden = 2
loc_table.dex = 3
loc_table.trainers = 4

item_clas.bagitem = 0
item_clas.multibagitem0 = 1
item_clas.multibagitem1 = 2
item_clas.multibagitem2 = 3
item_clas.specialbagitem = 4
item_clas.remote0 = 0xC
item_clas.remote1 = 0xD
item_clas.special = 0xE

hm.cut = "hm01"
hm.fly = "hm02"
hm.surf = "hm03"
hm.strength = "hm04"
hm.whirlpool = "hm05"
hm.rock_smash = "hm06"
hm.waterfall = "hm07"
hm.rock_climb = "hm08"
hm.flash = "tm70"

hm_badge.cut = "hive_badge"
hm_badge.fly = "storm_badge"
hm_badge.surf = "fog_badge"
hm_badge.strength = "plain_badge"
hm_badge.whirlpool = "glacier_badge"
hm_badge.rock_smash = "zephyr_badge"
hm_badge.waterfall = "rising_badge"
hm_badge.rock_climb = "earth_badge"

hm_tmhm_id.cut = 92
hm_tmhm_id.fly = 93
hm_tmhm_id.surf = 94
hm_tmhm_id.strength = 95
hm_tmhm_id.whirlpool = 96
hm_tmhm_id.rock_smash = 97
hm_tmhm_id.waterfall = 98
hm_tmhm_id.rock_climb = 99
hm_tmhm_id.flash = 69

item_group.battle_items = "Battle Items"
item_group.key_items = "Key Items"
item_group.badges = "Badges"
item_group.kanto_badges = "Kanto Badges"
item_group.johto_badges = "Johto Badges"
item_group.berries = "Berries"
item_group.pokedex = "Pokédex"
item_group.balls = "Balls"
item_group.tmhms = "TMs and HMs"
item_group.medicine = "Medicine"
item_group.mail = "Mail"
item_group.time = "Time Items"
item_group.sound = "Sound Items"
item_group.field_moves = "Field Machines"
item_group.hms = "HMs (actually Field Machines)"
item_group.tm28 = "TM28"
item_group.tm70 = "TM70"
item_group.hm01 = "HM01"
item_group.hm02 = "HM02"
item_group.hm03 = "HM03"
item_group.hm04 = "HM04"
item_group.hm05 = "HM05"
item_group.hm06 = "HM06"
item_group.hm07 = "HM07"
item_group.hm08 = "HM08"
item_group.dig = "Dig"
item_group.flash = "Flash"
item_group.cut = "Cut"
item_group.fly = "Fly"
item_group.surf = "Surf"
item_group.strength = "Strength"
item_group.whirlpool = "Whirlpool"
item_group.rock_smash = "Rock Smash"
item_group.waterfall = "Waterfall"
item_group.rock_climb = "Rock Climb"

reusable_evo_items = [
    "shiny_stone",
    "thunderstone",
    "moon_stone",
    "leaf_stone",
    "dusk_stone",
    "sun_stone",
    "fire_stone",
    "water_stone",
    "dawn_stone",
    "linking_cord",
]

nonreusable_evo_items = [
    "protector",
    "reaper_cloth",
    "deepseascale",
    "dragon_scale",
    "magmarizer",
    "deepseatooth",
    "metal_coat",
    "razor_claw",
    "razor_fang",
    "upgrade",
    "electirizer",
    "kings_rock",
    "dubious_disc",
    "oval_stone",
]

types = [
    "normal",
    "fighting",
    "flying",
    "poison",
    "ground",
    "rock",
    "bug",
    "ghost",
    "steel",
    "mystery",
    "fire",
    "water",
    "grass",
    "electric",
    "psychic",
    "ice",
    "dragon",
    "dark",
]

tm_moves = [
    "focus_punch",
    "dragon_claw",
    "water_pulse",
    "calm_mind",
    "roar",
    "toxic",
    "hail",
    "bulk_up",
    "bullet_seed",
    "hidden_power",
    "sunny_day",
    "taunt",
    "ice_beam",
    "blizzard",
    "hyper_beam",
    "light_screen",
    "protect",
    "rain_dance",
    "giga_drain",
    "safeguard",
    "frustration",
    "solar_beam",
    "iron_tail",
    "thunderbolt",
    "thunder",
    "earthquake",
    "return",
    "dig",
    "psychic",
    "shadow_ball",
    "brick_break",
    "double_team",
    "reflect",
    "shock_wave",
    "flamethrower",
    "sludge_bomb",
    "sandstorm",
    "fire_blast",
    "rock_tomb",
    "aerial_ace",
    "torment",
    "facade",
    "secret_power",
    "rest",
    "attract",
    "thief",
    "steel_wing",
    "skill_swap",
    "snatch",
    "overheat",
    "roost",
    "focus_blast",
    "energy_ball",
    "false_swipe",
    "brine",
    "fling",
    "charge_beam",
    "endure",
    "dragon_pulse",
    "drain_punch",
    "will_o_wisp",
    "silver_wind",
    "embargo",
    "explosion",
    "shadow_claw",
    "payback",
    "recycle",
    "giga_impact",
    "rock_polish",
    "flash",
    "stone_edge",
    "avalanche",
    "thunder_wave",
    "gyro_ball",
    "swords_dance",
    "stealth_rock",
    "psych_up",
    "captivate",
    "dark_pulse",
    "rock_slide",
    "x_scissor",
    "sleep_talk",
    "natural_gift",
    "poison_jab",
    "dream_eater",
    "grass_knot",
    "swagger",
    "pluck",
    "u_turn",
    "substitute",
    "flash_cannon",
    "trick_room",
    "cut",
    "fly",
    "surf",
    "strength",
    "whirlpool",
    "rock_smash",
    "waterfall",
    "rock_climb",
]

world_events = [
    "use_cut",
    "use_fly",
    "use_surf",
    "use_strength",
    "use_whirlpool",
    "use_rock_smash",
    "use_waterfall",
    "use_rock_climb",
    "use_flash",
]
